// <auto-generated />
using System;
using Bl.Financial.Size.Sample.Server.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bl.Financial.Size.Sample.Server.Migrations
{
    [DbContext(typeof(SqlFinancialContext))]
    partial class SqlFinancialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bl.Financial.Size.Sample.Application.Model.CompanyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MonthlyBilling")
                        .HasColumnType("DECIMAL(19, 4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("ServiceKind")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Bl.Financial.Size.Sample.Application.Model.NfAnticipationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Desagio")
                        .HasColumnType("DECIMAL(19, 4)");

                    b.Property<decimal>("LiquidValue")
                        .HasColumnType("DECIMAL(19, 4)");

                    b.Property<long>("NfId")
                        .HasColumnType("BIGINT");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("DECIMAL(19, 4)");

                    b.HasKey("Id");

                    b.ToTable("Anticipations");
                });

            modelBuilder.Entity("Bl.Financial.Size.Sample.Application.Model.NfModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("BIGINT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("DATE");

                    b.Property<long>("Number")
                        .HasColumnType("BIGINT");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(19, 4)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Nfs");
                });
#pragma warning restore 612, 618
        }
    }
}
